### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by tlworks** [Interverse/PvPChecks#2]
X marks the IP, hidden due to privacy reasons.

```
2018-11-10 11:24:58 - GetDataHandlers: ERROR: [9]|drocross| from `X` System.NullReferenceException: Object reference not set to an instance of an object.
   at PvPChecks.AntiPvPWeapons.OnPlayerUpdate(Object sender, PlayerUpdateEventArgs args)
   at TShockAPI.HandlerList`1.Invoke(Object sender, T e)
   at TShockAPI.GetDataHandlers.OnPlayerUpdate(Byte player, Byte control, Byte item, Vector2 position, Vector2 velocity, Byte pulley)
   at TShockAPI.GetDataHandlers.HandlePlayerUpdate(GetDataHandlerArgs args)
   at TShockAPI.GetDataHandlers.HandlerGetData(PacketTypes type, TSPlayer player, MemoryStream data)
```

**Comment by Interverse** [comment]
When does this occur?

**Comment by tlworks** [comment]
This issue still does seem to occur, how it happens is unknown to me until this day. I have not been able to debug this specific issue.

**Comment by tlworks** [comment]
Config file:
```
{
  "WeaponList": [
    "Last Prism",
    "Coin Gun"
  ],
  "BuffList": [
    198,
    58
  ]
}
```

**Comment by Interverse** [comment]
I attempted to fix the NullReferenceException in a new build. The download should be at https://github.com/Interverse/PvPChecks/blob/master/bin/Debug/PvPChecks.dll
