### ISSUE TITLE
OverFlowException

### ISSUE THREAD

**Issue by tlworks** [Interverse/PvPChecks#3]
X marks IP, hidden due to privacy. Unknown to why this happens.

```
2019-05-17 01:16:19 - GetDataHandlers: ERROR: [8]|melange| from X System.OverflowException: Negating the minimum value of a twos complement number is invalid.
   at System.Math.AbsHelper(Int32 value)
   at TShockAPI.GetDataHandlers.HandleNpcStrike(GetDataHandlerArgs args)
   at TShockAPI.GetDataHandlers.HandlerGetData(PacketTypes type, TSPlayer player, MemoryStream data)
```

**Comment by tlworks** [comment]
Config file:
```
{
  "WeaponList": [
    "Last Prism",
    "Coin Gun"
  ],
  "BuffList": [
    198,
    58
  ]
}
```

**Comment by Interverse** [comment]
Unsure if it's a problem with this plugin, as PvPChecks doesn't hook onto HandleNpcStrike.
