### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by tlworks** [Interverse/PvPChecks#4]
X marks the IP, hidden due to privacy reasons.

```
2019-05-17 03:19:42 - GetDataHandlers: ERROR: [2]|Tifari| from X System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Projectile.SetDefaultsDirect(Int32 Type)
   at Terraria.Projectile.SetDefaults(Int32 Type)
   at TShockAPI.TShock.CheckProjectilePermission(TSPlayer player, Int32 index, Int32 type)
   at TShockAPI.GetDataHandlers.HandleProjectileNew(GetDataHandlerArgs args)
   at TShockAPI.GetDataHandlers.HandlerGetData(PacketTypes type, TSPlayer player, MemoryStream data)
```

**Comment by tlworks** [comment]
Config file:
```
{
  "WeaponList": [
    "Last Prism",
    "Coin Gun"
  ],
  "BuffList": [
    198,
    58
  ]
}
```

**Comment by Interverse** [comment]
Unsure if it's a problem with this plugin, as PvPChecks doesn't hook onto HandleProjectileNew.
